[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_APP_URL = "https://app.agentevirtualia.com"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for SPA
[[redirects]]
  from = "/login"
  to = "https://app.agentevirtualia.com/auth"
  status = 302
  force = true

[[redirects]]
  from = "/register"
  to = "https://app.agentevirtualia.com/auth"
  status = 302
  force = true

[[redirects]]
  from = "/app/*"
  to = "https://app.agentevirtualia.com/:splat"
  status = 302
  force = true

# Enhanced Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://*.agentevirtualia.com; frame-ancestors 'none';"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-site"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, immutable, max-age=31536000"